global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: true
  rolling_window: false
  width: 30.0
  height: 30.0
  resolution: 0.08
  transform_tolerance: 0.5

  inflation_layer:
    inflation_radius: 1.3
    cost_scaling_factor: 5.0