local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 11.0
  height: 11.0
  resolution: 0.08
  transform_tolerance: 0.5

  # robot_radius: 0.3

  inflation_layer:
    inflation_radius: 0.2
    cost_scaling_factor: 10.0